### ISSUE TITLE
Landing page not readable in darkmode

### ISSUE THREAD

**Issue by mayrmartin** [openkfw/trubudget-website#6]
As pointed out [here](https://github.com/openkfw/TruBudget/issues/908), the landing page is not readable. This issue is will be resolved in the next TruBudget release 1.25.0.

**Comment by mushtaq96** [comment]
Hello is the bug fixed yet?

**Comment by jzakotnik** [comment]
@mayrmartin I guess this is open yet, right? @mushtaq96 wanted to have a look at it..

**Comment by mayrmartin** [comment]
@mushtaq96 thank you for offering your help on this issue! 😃 
The bug has not been addressed yet so you can fix it if you want. If you have any questions feel free to comment below we'll do our best to support you!

**Comment by mushtaq96** [comment]
> @mushtaq96 thank you for offering your help on this issue! 😃 The bug has not been addressed yet so you can fix it if you want. If you have any questions feel free to comment below we'll do our best to support you!

https://github.com/openkfw/TruBudget/tree/main/frontend
I am a bit confused here, this above link is the repo with Frontend files. 

However this is different? https://github.com/openkfw/trubudget-website

**Comment by mayrmartin** [comment]
This repository (https://github.com/openkfw/trubudget-website) is for our website which you can find at https://trubudget.net/ and should solely cover the purpose of making the documentation more accessible as well as have a web presence.
As part of the release process of TruBudget, the pipeline in our main repository ( https://github.com/openkfw/TruBudget/) where TruBudget actually lives, copies the documentation over here to this repository, invoices a pipeline, and the website gets rebuilt with the latest documentation.

This ticket addresses an issue with the website of TruBudget (hence this repository) where some parts of the website are not readable in dark mode.
![image](https://github.com/openkfw/trubudget-website/assets/22145802/4239a9ba-b026-4ebd-9dc4-7bd3e793b9cb)

I hope this helps, if you have any other questions feel free to comment below 😃

**Comment by mushtaq96** [comment]
@mayrmartin @jzakotnik Hello guys! I hope you can update the status of PR. This has been fixed.

**Comment by mayrmartin** [comment]
@mushtaq96  Thank you for the fix!
