### ISSUE TITLE
If dark mode is switched on, many components are rendered black on black

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/trubudget-website#80]

**Comment by mushtaq96** [comment]
@jzakotnik please assign me this issue so that I can work on it. Also a quick question,
Q. If I need some clarification on any part of the code or folder structure, whom do I need to get in contact with?

**Comment by jzakotnik** [comment]
@mushtaq96 your PR was merged. Much appreciated and many thanks for your effort on TruBudget!
